global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'app_metrics'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:80']
  - job_name: 'redis_metrics'
    static_configs:
      - targets: ['localhost:9121']