apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          limits:
            memory: "100Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: redis-volume
          mountPath: /etc/nginx/conf.d/default.conf
      volumes:
      - name: redis-volume
        hostPath:
          path: /Users/aniketpathak/Documents/Aniket/Code/ops-interview-task-master/app/nginx/conf.d/default.conf

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80

